name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate last updated timestamp
        run: |
          # Get the workflow ID for update-transcript.yml
          workflow_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | \
            jq -r '.workflows[] | select(.path == ".github/workflows/update-transcript.yml") | .id')
          
          # Get the latest successful run of the update-transcript workflow
          latest_run=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${workflow_id}/runs?status=success&per_page=1" | \
            jq -r '.workflow_runs[0].updated_at')
          
          # Check if we got a valid timestamp
          if [ "$latest_run" != "null" ] && [ -n "$latest_run" ]; then
            # Format the timestamp with UTC suffix
            formatted_date=$(date -d "$latest_run" +"%d %B %Y %H:%M" 2>/dev/null || echo "Recently")
            if [ "$formatted_date" != "Recently" ]; then
              echo "<span id=\"last-updated\">Last updated: $formatted_date UTC</span>" > partials/last-updated.html
            else
              echo "<span id=\"last-updated\">Last updated: Recently</span>" > partials/last-updated.html
            fi
          else
            echo "<span id=\"last-updated\">Last updated: Recently</span>" > partials/last-updated.html
          fi
          
          echo "Generated timestamp file:"
          cat partials/last-updated.html
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SMOKE_093D91003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SMOKE_093D91003 }}
          action: "close"

